In [7]:
import streamlit as st
import pandas as pd
import plotly.express as px

In [11]:
dfc = pd.read_csv('data/InternetSales.csv', encoding='latin1')

In [12]:
dfc.head()

,ProductName,ProductSubcategory,ProductCategory,Class,Color,DaysToManufacture,ModelName,Style,OrderDate,ShipDate,...,Age,MaritalStatus,Gender,YearlyIncome,TotalChildren,Education,Occupation,HouseOwnerFlag,NosCarsOwned,CommuteDistance
0,"Mountain-100 Silver, 38",Mountain Bikes,Bikes,H,Silver,4,Mountain-100,U,00:00.0,00:00.0,...,40,M,M,90000,2,Bachelors,Professional,1,0,1-2 Miles
1,"Mountain-200 Silver, 38",Mountain Bikes,Bikes,H,Silver,4,Mountain-200,U,00:00.0,00:00.0,...,42,M,M,90000,2,Bachelors,Professional,1,0,1-2 Miles
2,Fender Set - Mountain,Fenders,Accessories,NaN,NaN,0,Fender Set - Mountain,NaN,00:00.0,00:00.0,...,42,M,M,90000,2,Bachelors,Professional,1,0,1-2 Miles
3,"Touring-1000 Blue, 46",Touring Bikes,Bikes,H,Blue,4,Touring-1000,U,00:00.0,00:00.0,...,42,M,M,90000,2,Bachelors,Professional,1,0,1-2 Miles
4,Touring Tire,Tires and Tubes,Accessories,NaN,NaN,0,Touring Tire,NaN,00:00.0,00:00.0,...,42,M,M,90000,2,Bachelors,Professional,1,0,1-2 Miles

In [14]:
dfc.dtypes

ProductName            object
ProductSubcategory     object
ProductCategory        object
Class                  object
Color                  object
DaysToManufacture       int64
ModelName              object
Style                  object
OrderDate              object
ShipDate               object
DueDate                object
CustomerID              int64
Region                 object
Country                object
TerritoryGroup         object
Cost                  float64
SalesAmount           float64
TaxAmt                float64
Freight               float64
PromotionName          object
DiscountPct           float64
PromotionType          object
PromotionCategory      object
SalesOrderNumber       object
Currency               object
CustomerName           object
Age                     int64
MaritalStatus          object
Gender                 object
YearlyIncome            int64
TotalChildren           int64
Education              object
Occupation             object
HouseOwnerFlag          int64
NosCarsOwned            int64
CommuteDistance        object
dtype: object